name: Rust

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-util:

    runs-on: ${{ matrix.os }}
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            output: ptouch-util
            args: --no-default-features --features=util
          - target: armv7-unknown-linux-gnueabihf 
            os: ubuntu-latest
            output: ptouch-util
            apt-arch: armhf
          - target: x86_64-apple-darwin
            os: macos-latest
            output: ptouch-util
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            output: ptouch-util.exe
            args: --no-default-features --features=util

    steps:
    - uses: actions/checkout@v2
    - uses: FranzDiebold/github-env-vars-action@v1.2.1
      
    - name: Configure toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target:  ${{ matrix.target }}
        override: true
    
    - name: Configure caching 
      uses: actions/cache@v2
      # Caching disabled on macos due to https://github.com/actions/cache/issues/403
      if: ${{ matrix.os != 'macos-latest' }}
      with:
        key: ${{ matrix.os }}-${{ matrix.target }}
        path: |
          ${{ env.HOME }}/.cargo
          target

    - name: Install deps (brew)
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install libusb sdl2
    
    - name: Install deps (apt native)
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-gnu' }}
      run: sudo apt install -y libusb-dev libusb-1.0-0-dev

    - name: Install deps (foreign architecture)
      if: ${{ matrix.apt-arch }}
      uses: ryankurte/action-apt@v0.3.0
      with:
        arch: ${{ matrix.apt-arch }}
        packages: libusb-dev:${{ matrix.apt-arch }} libusb-1.0-0-dev:${{ matrix.apt-arch }} libsdl2-dev:${{ matrix.apt-arch }}

    - name: Install cross toolchain (armv7)
      if: ${{ matrix.target == 'armv7-unknown-linux-gnueabihf' }}
      run: sudo apt install gcc-arm-linux-gnueabihf

    - name: Enable cross compilation (armv7)
      if: ${{ matrix.target == 'armv7-unknown-linux-gnueabihf' }}
      run: |
        echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

    - name: Install libusb (vcpkg)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        vcpkg integrate install
        vcpkg install libusb:x64-windows-static
        echo "LIBUSB_DIR=C:/vcpkg/installed/x64-windows-static/" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Cache vcpkg
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/cache@v2
      with:
        key: ${{ matrix.os }}-${{ matrix.target }}
        path: $VCPKG_DIRECTORY

    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.use_cross }}
        command: build
        args: --target ${{ matrix.target }} --release ${{ matrix.args }}

    - name: Copy / Rename utility
      run: |
        cp target/${{ matrix.target }}/release/${{ matrix.output }} ${{ matrix.output }}-${{ matrix.target }}
        tar -czvf ptouch-util-${{ matrix.target }}.tgz ${{ matrix.output }}-${{ matrix.target }}

    - name: Upload utility artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output }}-${{ matrix.target }}
        path: ${{ matrix.output }}-${{ matrix.target }}

    - name: Upload utility binary to release
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ptouch-util-${{ matrix.target }}.tgz
        asset_name: ptouch-util-${{ matrix.target }}.tgz
        tag: ${{ github.ref }}
        overwrite: true

  release:
    name: Create release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Release ${{ github.ref }}

